import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Providers } from "./providers";

export const iranSans = localFont({
  src: [
    {
      path: "../../public/fonts/iransans/IRANSansXFaNum-UltraLightD4.woff",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansXFaNum-LightD4.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansXFaNum-RegularD4.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansXFaNum-MediumD4.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansXFaNum-SemiBoldD4.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansXFaNum-BoldD4.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansXFaNum-ExtraBoldD4.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansXFaNum-BlackD4.woff",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-iran-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`${iranSans.variable}`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
